[package]
name = "relaykit-tunnel"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
anyhow.workspace = true
futures-util.workspace = true
relaykit-protocol = { path = "../relaykit-protocol" }
ring.workspace = true
rustls.workspace = true
serde.workspace = true
tokio.workspace = true
tokio-tungstenite.workspace = true
tracing.workspace = true
url.workspace = true
